In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6,7]
b = a # now the reference of b is the same as a

In [3]:
a

[1, 2, 3, 4, 5, 6, 7]

In [4]:
b

[1, 2, 3, 4, 5, 6, 7]

In [5]:
b[1] = 0

In [6]:
b

[1, 0, 3, 4, 5, 6, 7]

In [7]:
a

[1, 0, 3, 4, 5, 6, 7]

a = [some list elements here]
1. in the memory, say at address 57828383, a list is created, and these elements are written there
2. "a" is now referencing to address 57828383, namely a = 57828383
b = a
1. b = a, since a = 57828383, b = 57828383


In [8]:
a = 5
b = a
b = 8
print(a)

5


# reshape:

a = np.array([some 3x4 array])
1. in memory, create 12 elements, they are written in one line, say, address = 510
2. a = list, 510, shape=3x4

a = a.reshape(4,3)?
1. a = list, 510, shape=4x3


In [9]:
a = np.array([5,4,3,4,5,6,3,3])
b = a.copy()
print(a)
print(b)

[5 4 3 4 5 6 3 3]
[5 4 3 4 5 6 3 3]


In [10]:
b[1] = -1
print(a)
print(b)

[5 4 3 4 5 6 3 3]
[ 5 -1  3  4  5  6  3  3]


In [12]:
a = np.array([10,12,43,20,150,230,7,5,300,10])

In [13]:
a

array([ 10,  12,  43,  20, 150, 230,   7,   5, 300,  10])

In [14]:
filt = [True, False, True, True, False, False, False, False, False, True]

In [15]:
filt

[True, False, True, True, False, False, False, False, False, True]

In [17]:
a[filt]

array([10, 43, 20, 10])

In [19]:
c = []
for i in range(len(a)):
    if filt[i]:
        c.append(a[i])
print(c)

[10, 43, 20, 10]


In [21]:
filt = a > 100

In [22]:
a[filt]

array([150, 230, 300])

In [23]:
a[a>100]

array([150, 230, 300])

In [24]:
a[a>100]

array([150, 230, 300])

In [27]:
a[a==300]

array([300])

In [28]:
np.exp(a)

array([2.20264658e+004, 1.62754791e+005, 4.72783947e+018, 4.85165195e+008,
       1.39370958e+065, 7.72201850e+099, 1.09663316e+003, 1.48413159e+002,
       1.94242640e+130, 2.20264658e+004])

In [29]:
np.sin(a)

array([-0.54402111, -0.53657292, -0.83177474,  0.91294525, -0.71487643,
       -0.6160642 ,  0.6569866 , -0.95892427, -0.99975584, -0.54402111])

In [30]:
np.cos(a)

array([-0.83907153,  0.84385396,  0.5551133 ,  0.40808206,  0.69925081,
       -0.78769594,  0.75390225,  0.28366219, -0.02209662, -0.83907153])

In [31]:
np.log(a)

array([2.30258509, 2.48490665, 3.76120012, 2.99573227, 5.01063529,
       5.43807931, 1.94591015, 1.60943791, 5.70378247, 2.30258509])

In [32]:
a[5] = 0

In [33]:
np.log(a)

/Users/i523375/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([2.30258509, 2.48490665, 3.76120012, 2.99573227, 5.01063529,
             -inf, 1.94591015, 1.60943791, 5.70378247, 2.30258509])

In [34]:
np.exp(a)

array([2.20264658e+004, 1.62754791e+005, 4.72783947e+018, 4.85165195e+008,
       1.39370958e+065, 1.00000000e+000, 1.09663316e+003, 1.48413159e+002,
       1.94242640e+130, 2.20264658e+004])

In [35]:
np.sqrt(a)

array([ 3.16227766,  3.46410162,  6.55743852,  4.47213595, 12.24744871,
        0.        ,  2.64575131,  2.23606798, 17.32050808,  3.16227766])

In [38]:
b = a.copy() * 5

In [39]:
b

array([  50,   60,  215,  100,  750,    0,   35,   25, 1500,   50])

In [40]:
a

array([ 10,  12,  43,  20, 150,   0,   7,   5, 300,  10])

In [41]:
b/a

/Users/i523375/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 5.,  5.,  5.,  5.,  5., nan,  5.,  5.,  5.,  5.])

In [42]:
b[5] = 700

In [43]:
b/a

/Users/i523375/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 5.,  5.,  5.,  5.,  5., inf,  5.,  5.,  5.,  5.])

In [44]:
1/a

/Users/i523375/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.1       , 0.08333333, 0.02325581, 0.05      , 0.00666667,
              inf, 0.14285714, 0.2       , 0.00333333, 0.1       ])

In [45]:
a

array([ 10,  12,  43,  20, 150,   0,   7,   5, 300,  10])

In [46]:
a**2

array([  100,   144,  1849,   400, 22500,     0,    49,    25, 90000,
         100])

In [47]:
a+50

array([ 60,  62,  93,  70, 200,  50,  57,  55, 350,  60])

In [48]:
a-b

array([  -40,   -48,  -172,   -80,  -600,  -700,   -28,   -20, -1200,
         -40])

In [49]:
a-100

array([ -90,  -88,  -57,  -80,   50, -100,  -93,  -95,  200,  -90])